apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: tanzu-postgresql-accelerator
spec:
  displayName: Tanzu PostgreSQL
  description: Tanzu PostgreSQL
    
    
  iconUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Spring_Framework_Logo_2018.svg/800px-Spring_Framework_Logo_2018.svg.png
  tags:
    - data-service
    - postgresql
  git:
    ignore: ".git/, target, catalog"
    url: https://github.com/gorkemozlu/tanzu-postgres-on-tap
    ref:
      branch: main